name: Deploy Portfolio Site

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Root folder, change if site files are in subfolder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

